char *mensaje_de_error[] = { "",
/*Error 1 */ "Hace falta ';' ',' .",
/*Error 2 */ "Hace falta un identificador .",
/*Error 3 */ "Hace falta '=' . ",
/*Error 4 */ "Hace falta '}' o '{' .",
/*Error 5 */ "Hace falta '(' o ')' .",
/*Error 6 */ "Se omitio la palabra reservada 'ASIGN' .",
/*Error 7 */ "Se esperaba la palabra reservada 'NEW' .",
/*Error 8 */ "Se esperaba la palabra reservada 'CLASS' .",
/*Error 9 */ "Se esperaba la palabra reservada 'IF' .",
/*Error 10*/ "Se esperaba la palabra reservada 'ELSE'",
/*Error 11*/ "Se esperaba la palabra reservada 'WHILE'",
/*Error 12*/ "Hace falta token '-' o '+' ",
/*Error 13*/ "Hace falta token '*' o '/' ",
/*Error 14*/ "Hace falta token '<->' ",
/*Error 15*/ "Se esperaba la palabra reservada START",
/*Error 16*/ "Se esperaba la palabra reservada END",
/*Error 17*/ "Se esperaba la palabra reservada PUBLIC",
/*Error 18*/ "Se esperaba la palabra reservada EXC",
/*Error 19*/ "Se esperaba una (condicion aumento o disminucion)",
/*Error 20*/ "Se esperaba un numero",
/*Error 21*/ "Hace falta un <= o >= o < o > o == o !=",
/*Error 22*/ "Se esperaba la palabra reservada FOR",
/*Error 23*/ "el factor anterior no puede ir seguido de este simbolo o falta un punto y coma",
/*Error 24*/ "una expresion no puede empezar con este simbolo",
/*Error 25*/ "Se esperaba la palabra reservada BREAK",
/*Error 26*/ "Se esperaba la palabra reservada CASE",
/*Error 27*/ "Se esperaba la palabra reservada DEFAULT",
/*Error 28*/ "Se esperaba la palabra reservada SWITCH",
/*Error 29*/ "Se esperaban comillas dobles",
/*Error 30 NO TOCAR*/ "NUMERO demasiado grande - trunc(5)",
/*Error 31*/ "Se esperaba una cadena de caracteres",
/*Error 32*/ "Se esperaba una comparacion ==",
/*Error 33*/ "Se esperaba != ",
/*Error 34*/ "Se esperaba comillas dobles ",
/*Error 35*/ "Se esperaba la palabra reservada PRINT",
/*Error 36*/ "No se encontro una instrucción (if,while,for,switch)",
/*Error 37*/ "Se esperaba el token void",
/*Error 38*/ "Se esperaba un tipo de varaible",
/*Error 39*/ "",
/*Error 40*/ "No puede ir un ELSE sin un IF",
/*Error 41*/ "READ debe ir seguido de un parentesis abierto",
/*Error 42*/ "falta un identificador despues del parentesis",
/*Error 43*/ "falta un identificador despues de la coma",
/*Error 44*/ "WRITE debe ir seguido de un parentesis abierto",
/*Error 45*/ "falta un identificador o expresion despues del parentesis",
/*Error 46*/ "se espera un INCLUDE",
/*Error 47*/ "se esperan COMILLAS",
/*Error 48*/ "se espera la obdumath.h",
/*Error 49*/ "la funcion trigonometrica debe ir seguido de un parentesis",
/*Error 50*/ "para poder utilizar las funciones trigonometricas matematicas debe utilizar la libreria OBDUMATH",
/*Error 51*/ "falta un identificador o numero despues del parentesis",
/*Error 52*/ "la funcion POW necesita dos parametros separados por coma",
/*Error 53*/ "se espera un identificador o cadena(entre comillas simples)",
/*Error 54*/ "falta la comilla de cierre"};
